server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: educare-app

  datasource:
    url: jdbc:postgresql://localhost:5432/EDU_CARE
    username: postgres
    password: 778080aA@
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:file:backend/.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: ${JWT_SIGNER_KEY}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-southeast-1
  s3:
    bucket-name: educare-upload-2026